gogonzogo/Slimmom

package-lock.json, package.json, src/components/Header.jsx, src/hooks/useViewport.js
mui icon material dependency may not be needed for long. I will uninstall it if it is not needed later. 
🤤 I did not add the component to the app. Feel free to do so if you are ready.
=> header start

public/manifest.json, src/components/Header/Header.jsx, src/components/caloriesCalc/caloriesCalc.jsx, src/components/logo/logo.jsx, src/pages/Calculator/Calculator.jsx, src/pages/Diary/Diary.jsx, src/pages/Home/Home.jsx
=> [capitalized jsx component folder and file names as well as updated logo route]

public/manifest.json, src/components/Header/Header.jsx, src/components/caloriesCalc/caloriesCalc.jsx, src/components/logo/logo.jsx, src/pages/Calculator/Calculator.jsx, src/pages/Diary/Diary.jsx, src/pages/Home/Home.jsx
Reverts gogonzogo/Final-Team-Project#12
=> Revert "[capitalized jsx component folder and file names as well as updated logo route]"

src/components/Modal/Modal.jsx, src/components/Modal/ModalContainer.js, src/components/Modal/modal.module.css, src/components/caloriesCalc/caloriesCalc.jsx
need redux to add live changes
=> added modal window

src/components/App.jsx, src/index.js, src/theme/Theme/theme.js
delete backslash on basename
add theme
=> update basename insert theme files

src/components/PrivateRoute/PrivateRoute.jsx, src/components/PublicRoute/PublicRoute.jsx
They are commented out until redux logic is implemented
=> public and private route components

src/pages/Calculator/Calculator.jsx, src/pages/Diary/Diary.jsx, src/pages/Login/Login.jsx, src/pages/Register/Register.jsx, src/theme/Theme/theme.js
=> add containers to the pages

src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/login.module.css
Completed some of the form styling for mobile version
=> Login form

package-lock.json, src/components/Header/Header.jsx, src/components/Header/Header.module.css, src/components/Logo/Logo.module.css, src/components/Navigation/Navigation.jsx, src/components/Navigation/Navigation.module.css, src/pages/Home/Home.jsx
🐞 need to fix padding on header-- it rendered correctly with padding 20 40 a couple times -- I think when I added the padding for the desktop version it broke...
=> update home page header

src/components/Header/Header.jsx, src/components/Header/Header.module.css, src/components/Navigation/Navigation.jsx, src/components/Navigation/Navigation.module.css, src/index.css, src/theme/Theme/theme.js
still need to work with largest screen size. the vertical grey line may need to be applied to the logo instead of the navigation, when the logo gets bigger, the spacing crunches
=> updated header padding more

src/components/Header/Header.jsx, src/components/Logo/Logo.jsx, src/components/Logo/Logo.module.css
padding margin and gray line placement
=> home header fix

src/components/App.jsx, src/index.js
move theme provider to index.js
=> update theme provider loction

src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserInfo.module.css
skeleton userInfo component-- 
not attached to Header yet, so will not be visible unless you import it. Not much to look at though yet
=> UserInfo framework

package-lock.json, src/components/CaloriesCalc/CaloriesCalc.jsx, src/components/CaloriesCalc/CaloriesCalc.module.css, src/components/Modal/modal.module.css, src/components/RightSideBar/RightSideBar.jsx, src/components/RightSideBar/rightSideBar.module.css, src/index.css, src/redux/auth/authSlice.js
1) The sidebar was added, but I don't know how I can expand it on the desktop view to be 100% on the whole screen.
2) Changed styles for a modal, so now it has a scroll in case people flip their phones or do anything else when their screen is really wide and not tall.
3) Changed a lot of styles of CaloriesCalc.jsx, to be able to position the sidebar properly. Jim, if you are reviewing this pull request - don't yell :)
=> added side bar on calculator page

package-lock.json, src/components/DiaryAddProductForm/DiaryAddProductForm.jsx, src/components/DiaryCalendar/DiaryCalendar.jsx, src/components/ProductsList/AllProductsList/AllProductsList.jsx, src/pages/Diary/Diary.jsx
=> Diary calendar

src/components/CaloriesCalc/CaloriesCalc.jsx, src/components/CaloriesCalc/CaloriesCalc.module.css, src/components/RightSideBar/RightSideBar.jsx, src/components/RightSideBar/rightSideBar.module.css, src/index.css, src/pages/Calculator/Calculator.jsx, src/pages/Diary/Diary.jsx, src/pages/Home/Home.jsx
=> side bar resubmit

src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/login.module.css
- worked on tablet and desktop layout for login form
=> tablet and desktop layout

package-lock.json, src/components/Header/Header.jsx, src/components/Logo/ImageLogo.jsx, src/components/Logo/Logo.jsx, src/components/Logo/Logo.module.css, src/components/Logo/TextLogo.jsx, src/components/Navigation/Navigation.jsx, src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserInfo.module.css, src/components/UserInfo/UserToolBar.jsx
😀add fake loginInfo to header to mock logic
😀create TextLogo and ImageLogo to isolate Logo parts for sliding functionality and ease of screen rendering 😄added new logos to header and userInfo
😅 add logic for screen size and logged in rendering 
🐞 still need to work out spacing and add redux
=> work on userinfo/ nav/ header/logo components

package-lock.json, src/components/Header/Header.jsx, src/components/Logo/ImageLogo.jsx, src/components/Logo/Logo.jsx, src/components/Logo/Logo.module.css, src/components/Logo/TextLogo.jsx, src/components/Navigation/Navigation.jsx, src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserInfo.module.css, src/components/UserInfo/UserToolBar.jsx
=> Revert "Revert "work on userinfo/ nav/ header/logo components""

src/components/LoginForm/LoginForm.jsx, src/components/RegistrationForm/RegistrationForm.jsx, src/components/RegistrationForm/RegistrationForm.module.css
needs validation popup styles
Added route to login form button
=> Registration Form has same styles as Login Form

src/components/CaloriesCalc/CaloriesCalc.jsx, src/components/CaloriesCalc/CaloriesCalc.module.css
change the radio buttons to orange when clicked and move the form to the left side of the page.  still trying to figure out how to changes the label color
=> edit calculate form

src/components/RegistrationForm/RegistrationForm.jsx, src/redux/auth/authOperations.js, src/redux/validation/registrationSlice.js
The user is able to register and receive a notification that it was successfully done! And the user is sent to the back end. I still need to make sure the user is getting the proper error messages. And perhaps they should be re directed to the login page after registered.
=> Registration connected to backend - not finished

package-lock.json, src/components/Header/Header.jsx, src/components/Logo/TextLogo.jsx, src/components/Navigation/Navigation.jsx, src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserInfo.module.css, src/components/UserInfo/UserToolBar.jsx
😀 adjusted mobile and tablet styles... may still need to adjust padding 
🐞 still need to figure out animation to navigation component, the logic works on the button but not the nav. 
🐜🐜🐜 still need to adjust the desktop version. waiting on logo
=> adjust styling

src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/login.module.css, src/redux/auth/authOperations.js
- updated styles
- checked post requests
- checked validation
- checked errors
=> login final changes

src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/login.module.css
- fixed the button hover color to display correctly 
- reformatted my code with prettier
=> Login form validation

src/components/Button/Button.jsx, src/components/Button/Button.module.css, src/components/Button/CirclePlus.module.css, src/components/RegistrationForm/RegistrationForm.jsx, src/components/RegistrationForm/RegistrationForm.module.css
Validation popup is now added to the form field
=> Button.jsx is updated and reusable

src/components/App.jsx, src/components/CaloriesCalc/CaloriesCalc.module.css, src/components/Container/Container.jsx, src/components/DiaryAddProductForm/DiaryAddProductForm.module.css, src/components/DiaryCalendar/DiaryCalendar.module.css, src/components/DiaryList/style.module.css, src/components/Header/Header.jsx, src/components/LoginForm/login.module.css, src/components/Navigation/Navigation.jsx, src/components/Section/Section.jsx, src/index.css, src/pages/Calculator/Calculator.jsx, src/pages/Diary/Diary.jsx, src/pages/Home/Home.jsx, src/pages/Login/Login.jsx, src/pages/Register/Register.jsx
I either commented out or deleted padding or margin conflicts on major component elements. still needs tweaking
=> adding section and container

src/components/Header/Header.jsx, src/components/Navigation/Navigation.jsx, src/components/UserInfo/UserToolBar.jsx, src/hooks/useAuth.js, src/redux/auth/authOperations.js
dispatch and operator for logout
useAuth for loggedIn
=> call redux for loggedIn and logOut

src/components/Navigation/Navigation.jsx, src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserInfo.module.css
=> working out slider nav

src/components/DiaryAddProductForm/DiaryAddProductForm.jsx, src/components/DiaryList/DiaryList.jsx, src/components/LoginForm/LoginForm.jsx, src/components/UserInfo/UserInfo.jsx, src/redux/auth/authOperations.js, src/redux/diary/diaryOperations.js
Reverts gogonzogo/Final-Team-Project#126
=> Revert "[patch backend connection and removed console.logs]"

src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserInfo.module.css
slight bug fix possible -- does not slide out
=> slider nav a go on toggle

src/components/CaloriesCalc/CaloriesCalc.jsx, src/redux/Calc/calcOperations.js, src/redux/Calc/calcSlice.js, src/redux/Calc/calcSliceSelectors.js
calculates the total calories and pass the no allowed food.
=> calculator API

src/components/LoginForm/login.module.css, src/index.css, src/pages/Login/Login.jsx
padding and margin adjustments
=> update container styling

src/components/RegistrationForm/RegistrationForm.module.css, src/pages/Register/Register.jsx
=> update page spacing

src/components/CaloriesCalc/CaloriesCalc.module.css, src/pages/Home/Home.jsx
=> container styled

src/components/DiaryCalendar/DiaryCalendar.module.css, src/index.css, src/pages/Diary/Diary.jsx
=> diary calendar styles

src/pages/Login/Login.jsx
Reverts gogonzogo/Final-Team-Project#144
=> Revert "resolved conflict"

src/components/RightSideBar/rightSideBar.module.css, src/index.css, src/pages/Calculator/Calculator.jsx, src/pages/Diary/Diary.jsx
added linear gradient. removed background color from sidebar component. needsBUG FIX: double check background images for desktop rendering tablet image
=> update background image

package-lock.json, src/components/Header/Header.jsx, src/components/RightSideBar/rightSideBar.module.css, src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserToolBar.jsx, src/index.css, src/pages/Diary/Diary.jsx, src/pages/Login/Login.jsx
=> extended background image

src/components/DiaryCalendar/DiaryCalendar.module.css, src/components/Header/Header.jsx, src/components/UserInfo/UserInfo.jsx, src/components/UserInfo/UserToolBar.jsx, src/hooks/useViewport.js, src/index.css, src/redux/auth/authOperations.js
removed slide of toggle on logged in.
working on managing a fixed header
=> working on spacing

src/components/App.jsx, src/components/Header/Header.jsx, src/components/PrivateRoute/PrivateRoute.jsx, src/components/PublicRoute/PublicRoute.jsx, src/components/UserInfo/UserToolBar.jsx, src/index.css
works on login and registration
BUG FIX for logout and user name
Also adjusted the background to fill the page in the index.css file
=> implement public and private routes

src/components/App.jsx, src/components/Header/Header.jsx, src/components/PrivateRoute/PrivateRoute.jsx, src/components/PublicRoute/PublicRoute.jsx, src/components/RightSideBar/rightSideBar.module.css, src/components/UserInfo/UserInfo.module.css, src/index.css, src/pages/Diary/Diary.jsx, src/pages/Home/Home.jsx
remove fixed header and revert as much as possible. kept z-index on sidebar so it would go behind the background image. Not sure how, but the header is no longer blocking the sidebar.
=> return styling to previous setting

src/index.css, src/pages/Home/Home.jsx
=> working on images

package-lock.json, package.json, src/components/UserInfo/UserToolBar.jsx
required npm i for font awesome icons
=> change logout logo idea

src/components/Modal/ListWithScroll.jsx, src/components/Modal/Modal.jsx, src/components/RightSideBar/Summary.jsx, src/components/RightSideBar/SummaryContainer.jsx, src/components/RightSideBar/rightSideBar.module.css, src/redux/Calc/calcOperations.js, src/redux/Calc/calcSlice.js, src/redux/Calc/calcSliceSelectors.js
Search works just by querry for now. Will change it so it searches by blood type too tomorrow
=> added search by querry

.env, src/components/CaloriesCalc/CaloriesCalc.jsx, src/components/LoginForm/LoginForm.jsx, src/components/RegistrationForm/RegistrationForm.jsx
use the enter key to mover between fields on the registration, login and calculator
=> use enter key

src/components/LoginForm/LoginForm.jsx, src/components/RegistrationForm/RegistrationForm.jsx
convert the email to lowercase before sending in login and registration page
=> convert email to lower

src/components/LoginForm/LoginForm.jsx, src/components/RegistrationForm/RegistrationForm.jsx
email to lowercase registration form
=> email to lowercase

src/components/UserInfo/UserToolBar.jsx
change the z-index to move the logout button up front
=> change z-index logout

src/components/CaloriesCalc/CaloriesCalc.jsx, src/components/RightSideBar/Stats.jsx
change message when no calculator
=> change message when no calculator

src/components/UserInfo/UserToolBar.jsx
correct type needed capital I in index
=> correct typo

src/components/RegistrationForm/RegistrationForm.jsx, src/components/UserInfo/UserToolBar.jsx
adding a record to the calculator table if registering from the calculator page
=> add to calculator on registration

src/redux/Calc/calcOperations.js, src/redux/Calc/calcSlice.js
deleted unused fetchDaySummary
=> deleted fetchDaySummary

src/components/RegistrationForm/RegistrationForm.jsx
fix sidebar to show info when calculator submit
=> fix sidebar

src/index.css, src/redux/Calc/calcOperations.js, src/redux/auth/authOperations.js, src/redux/auth/authSlice.js, src/redux/store.js
Login logout  and registration messages on fulfilled and rejected implemented
=> update login alerts

src/components/DiaryAddButton/DiaryAddButton.module.css, src/components/ThemeSwitch/ThemeSwitch.jsx, src/components/ThemeWrapper/ThemeWrapper.jsx, src/index.js, src/pages/Calculator/Calculator.jsx, src/pages/Login/Login.jsx, src/redux/auth/authOperations.js, src/redux/auth/authSlice.js, src/redux/theme/themeSelectors.js, src/redux/theme/themeSlice.js, src/theme/theme.js
update them to remove baseTheme
refactor for v5 syntax, using mode instead of type.
=> refactor for MUI V5 theme

src/components/ThemeButton/ThemeButton.jsx, src/components/ThemeButton/ThemeButton.module.css, src/index.css
Sun working
🐞🐞🐞moon still backwards
=> theme button hover

src/components/App.jsx, src/components/CustomButton/CustomButton.module.css, src/components/FooterAcct/FooterAcct.jsx, src/components/Modal/ModalAcct.jsx, src/components/Modal/modal.module.css, src/pages/Footer/Footer.js, src/redux/auth/authOperations.js
Add account setting to the footer and display only when logged in
=> Add account setting to footer

src/components/CustomButton/CustomButton.module.css, src/components/DiaryAddButton/DiaryAddButton.module.css, src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/login.module.css, src/components/RegistrationForm/RegistrationForm.jsx, src/index.css
update login button disabled
updated variables in custom button module
updated variable in addButton
=> little fixes

src/components/CaloriesCalc/CaloriesCalc.jsx, src/components/CaloriesCalc/CaloriesCalc.module.css, src/components/CustomButton/CustomButton.module.css, src/components/DiaryAddButton/DiaryAddButton.module.css, src/components/DiaryCalendar/DiaryCalendar.module.css, src/components/Heading/Heading.jsx, src/components/Heading/Heading.module.css, src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/login.module.css, src/components/RightSideBar/rightSideBar.module.css, src/components/ThemeButton/ThemeButton.jsx, src/components/ThemeButton/ThemeButton.module.css, src/index.css, src/pages/Diary/Diary.jsx, src/theme/theme.js
--remove mui ripple and auto hover
add diary heading w/ new heading component
adjust color for disabled logic
=> theme tweaks

src/index.css, src/pages/Footer/Footer.jsx, src/pages/Footer/Footer.module.css
😄 center squad info and add link to project readme 😄 bring styling to not logged in render
=> footer styling

src/components/Avatar/AvatarImg.jsx, src/components/Avatar/AvatarImg.module.css
increase avatar size
add right margin
=> add styling

src/components/CaloriesCalc/CaloriesCalc.module.css, src/components/Heading/Heading.module.css, src/pages/Diary/Diary.jsx, src/pages/Diary/Diary.module.css
=> make diary and calc responsive

src/pages/Footer/Footer.jsx, src/pages/Footer/Footer.module.css
adjust padding based on logged in
=> conditional padding

src/components/CustomButton/CustomButton.module.css, src/components/RightSideBar/Stats.jsx, src/components/RightSideBar/Summary.jsx
add graph to calculator and format the button
=> add graph to calculator

src/components/DiaryAddProductForm/DiaryAddProductForm.jsx, src/redux/auth/authSlice.js
Fix login rejected toast not distinguishing between server error and incorrect password
=> login error message
